apiVersion: apps/v1
kind: Deployment
metadata:
  name: mshop-db
spec:
  selector:
    matchLabels:
      app: mshop-db
  template:
    metadata:
      labels:
        app: mshop-db
    spec:
      containers:
      - name: mshop-db
        image: bitnami/mysql:8.3.0
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MYSQL_DATABASE
          value: "monitor-shop"
        ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mshop-db
spec:
  selector:
    app: mshop-db
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mshop-db-expose
spec:
  type: NodePort
  selector:
    app: mshop-db
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30008
