apiVersion: apps/v1
kind: Deployment
metadata:
  name: mshop-minio
spec:
  selector:
    matchLabels:
      app: mshop-minio
  template:
    metadata:
      labels:
        app: mshop-minio
        proj: mshop
    spec:
      containers:
      - name: mshop-minio
        image: bitnami/minio:latest
        env:
        - name: MINIO_ROOT_USER
          value: "minioadmin"
        - name: MINIO_ROOT_PASSWORD
          value: "minioadmin"
        ports:
        - containerPort: 9000
        - containerPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: mshop-minio
spec:
  selector:
    app: mshop-minio
  ports:
  - port: 9000
    targetPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: mshop-minio-admin
spec:
  type: NodePort
  selector:
    app: mshop-minio-admin
  ports:
  - port: 9001
    targetPort: 9001
    nodePort: 30901
