FROM giangndj/jdk:17 AS build

WORKDIR /app
COPY ./src /app/src
COPY ./pom.xml /app/pom.xml
RUN mvn package


FROM eclipse-temurin:17.0.12_7-jre-noble
WORKDIR /app
COPY --from=build /app/target/*.jar /app/app.jar

ENV server_port=80
ENV active_profile=sv

CMD ["java","-Dspring.profiles.active=${active_profile}", "-Dserver.port=${server_port}", "-jar", "app.jar"]
