apiVersion: apps/v1
kind: Deployment
metadata:
  name: mshop-rabbitmq
spec:
  selector:
    matchLabels:
      app: mshop-rabbitmq
  template:
    metadata:
      labels:
        app: mshop-rabbitmq
        proj: mshop
    spec:
      containers:
      - name: mshop-rabbitmq
        image: bitnami/rabbitmq:latest
        env:
        - name: RABBITMQ_USERNAME
          value: "mshop"
        - name: RABBITMQ_PASSWORD
          value: "123456"
        - name: RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS
          value: "true"
        ports:
        - containerPort: 5672
        - containerPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: mshop-rabbitmq
spec:
  selector:
    app: mshop-rabbitmq
  ports:
  - port: 5672
    targetPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: mshop-rabbitmq-expose
spec:
  type: NodePort
  selector:
    app: mshop-rabbitmq
  ports:
  - port: 15672
    targetPort: 15672
    nodePort: 30672
