apiVersion: apps/v1
kind: Deployment
metadata:
  name: mshop-redis
spec:
  selector:
    matchLabels:
      app: mshop-redis
  template:
    metadata:
      labels:
        app: mshop-redis
        proj: mshop
    spec:
      containers:
      - name: mshop-redis
        image: bitnami/redis:5.0.14
        env:
        - name: REDIS_PASSWORD
          value: "123456"
        - name: REDIS_MASTER_PASSWORD
          value: "123456"
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: mshop-redis
spec:
  type: NodePort
  selector:
    app: mshop-redis
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30379
