apiVersion: apps/v1
kind: Deployment
metadata:
  name: mshop-api-gateway-service
spec:
  selector:
    matchLabels:
      app: mshop-api-gateway-service
  template:
    metadata:
      labels:
        app: mshop-api-gateway-service
        proj: mshop
    spec:
      containers:
      - name: mshop-api-gateway-service
        image: giangndj/mshop:api-gateway-service
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mshop-api-gateway-service-expose
spec:
  selector:
    app: mshop-api-gateway-service
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30099

