apiVersion: apps/v1
kind: Deployment
metadata:
  name: mshop-fe-admin
spec:
  selector:
    matchLabels:
      app: mshop-fe-admin
  template:
    metadata:
      labels:
        app: mshop-fe-admin
        proj: mshop
    spec:
      containers:
      - name: mshop-fe-admin
        image: giangndj/mshop:fe-admin
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mshop-fe-admin
spec:
  selector:
    app: mshop-fe-admin
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30090
  type: NodePort

